### ISSUE TITLE
Giving hints to RetDec

### ISSUE THREAD

**Issue by v-p-b** [ThisIsSecurity/retdec_offline#1]
I have a target that uses some kind of custom calling convention. This is resolved nicely by Binary Ninja, but not by RetDec. 

Is there a preferred way (either through configuration or code) to give hints to RetDec about calling conventions and similar properties (such as function signature) of the target? 

It seems that the IDA Plugin is already capable of passing this kind of information, maybe retdec_offline could implement a similar approach:

https://github.com/avast-tl/retdec-idaplugin/blob/9cfc4a3ccfe3372df70d3f8855dea768ecf5c59f/src/idaplugin/config_generator.cpp#L109

**Comment by paulfariello** [comment]
It would be great to support calling conventions. But we currently rely on the simple `retdec-decompiler.sh` and it doesn't seem to support such an option. There is two option for us here:

1. full rewrite of our plugin to directly call retdec (like the IDA plugin)
2. open a feature request on retdec to add the missing option

**Comment by paulfariello** [comment]
My bad, IDA is using `retdec-decompiler.sh` too. So we just have to produce the right config file.

**Comment by paulfariello** [comment]
7131cd2 should fix your issue. Please let us know if you have any issue with it.

**Comment by v-p-b** [comment]
I'm still having issues with this: Binary Ninja detects that the function uses fastcall convention and expects 3 arguments (seems right) but the decompiled code only shows a single argument in the function definition.
