### ISSUE TITLE
MacOS cannot find FILE argument

### ISSUE THREAD

**Issue by ghost** [ThisIsSecurity/retdec_offline#12]
MacOS 10.14.3 (18D109) Pygments(2.7.3) python 3.7.2 Binary Ninja 1.1.1470
ERROR:
retdec-decompiler.py: error: the following arguments are required: FILE
failed to decompile function: [Errno 2] No such file or directory: '/var/folders/n2/w8h2wjh51_35gjyg5j3kmtqm0000gn/T/tmpq81z9x.c'

**Comment by valbaudo** [comment]
I have the same problem on Linux

**Comment by trippleflux** [comment]
Also having the same problem in windows now

**Comment by trippleflux** [comment]
The 'fixes' or workaround is on issue #10
